all:
	@echo "make install instead"

install:
	mkdir -p /var/www/slurmbrowser
	cp slurmdata.py Metrics.py default.gif squeue.html nodeinfo.html job.html jobhist.html hostlist.py /var/www/slurmbrowser/

clean:
	rm -f *~ *.pyc


